---
services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9
    container_name: zookeeper
    restart: unless-stopped
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - 127.0.0.1:2181:2181
    volumes:
      - "zookeeper_data:/bitnami"

  kafka:
    image: bitnami/kafka:3.5.0
    container_name: kafka
    restart: unless-stopped
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CREATE_TOPICS=Kafka:1:1
    ports:
      - ${KAFKA_HOST}:${KAFKA_PORT}:${KAFKA_PORT}
    depends_on:
      - zookeeper
    volumes:
      - 'kafka_data:/bitnami/kafka'

  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=test
    ports:
      - ${POSTGRES_HOST}:${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres:/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web-backend:
    build: .
    container_name: web
    restart: always
    environment:
      - POSTGRES_HOST=postgres
      - UVICORN_HOST=0.0.0.0
    command: /bin/sh -cx "./start.sh"
    ports:
      - ${UVICORN_HOST}:${UVICORN_PORT}:${UVICORN_PORT}
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy

volumes:
  postgres:
  kafka_data:
  zookeeper_data:
